name: Showroom shell Vercel Deployment

on:
  push:
    branches:
      - main
    paths:
      - "apps/shell/**"
      - ".github/workflows/shell_vercel_deploy.yaml"

jobs:
  Deploy-Production:
    runs-on: ubuntu-latest

    environment: "Production â€“ showroom-shell"
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

    steps:
      - uses: actions/checkout@v2

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Add remotes address file to assets
        run: |
          cat << EOF > $HOME/work/showroom/showroom/.vercel/output/static/assets/remote-urls.json
          {
            "fe-mat": "https://showroom-fe-mat.vercel.app/",
            "fe-bs": "https://showroom-fe-bs.vercel.app/"
          }
          EOF

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
